extra_joints:
    - name: 'caster_left_1_joint'
    - name: 'caster_left_2_joint'
    - name: 'caster_left_3_joint'
    - name: 'caster_right_1_joint'
    - name: 'caster_right_2_joint'
    - name: 'caster_right_3_joint'
    - name: 'rotacaster_right_joint'
    - name: 'rotacaster_left_joint'
